/* Requires the Docker Pipeline plugin */
pipeline {
    agent { any { image 'maven:3.9.5' } }
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
            }
        }
    }
}